name: soundvetx

services:
  app:
    image: soundvetx-app:latest
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - soundvetx-network

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${DATABASE_TZ}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - soundvetx-network
 
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - soundvetx-network
 
volumes:
  db-data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  soundvetx-network:
    driver: bridge