services:
  app:
    image: soundvetx-app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    networks:
      - soundvetx-network

  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${DATABASE_TZ}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - soundvetx-network
 
  adminer:
    restart: always
    image: adminer
    ports:
      - 8080:8080
    networks:
      - soundvetx-network
 
volumes:
  pgdata:

networks:
  soundvetx-network:
    driver: bridge